# -*- coding: utf-8 -*-
"""Python_Basic_Bhaskar.py

Automatically generated by Colab.

Original file is located at
    https://colab.research.google.com/drive/1cgAcIvdJZhpSx85JAe7Ljr5fq4WokyRJ
"""

Name = "P BHASKAR NAIK"

Age = 22

Height = 5.4

is_student = True

print(Name,Age,Height,is_student)

print("Name :",Name,"Age:",Age,"Height:",Height,"Student:",is_student)

Age_in_Months = Age *12

Age_in_Days = Age *365

Remainder = Age % 7

Age_Power_2 = Age ** 2

print("Age in months:",Age_in_Months)

print("Age in Days : ",Age_in_Days)

print("Remainder when age is divided by 7:",Remainder)

print("Age raised to the power of 2 :",Age_Power_2)